name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true
      - name: Build tester
        run: |
          cd testing
          make all
      - name: Install valgrind
        run: sudo apt install --no-install-recommends -y valgrind
      - name: Run valgrind
        run: |
          valgrind --leak-check=full \
                   --show-leak-kinds=all \
                   --track-origins=yes \
                   --verbose \
                   --log-file=valgrind-out.txt \
                   testing/test
        env:
          FARL_LOG: $GITHUB_WORKSPACE/testing/test.log
          FARL_YAML: $GITHUB_WORKSPACE/testing/test.yaml
