name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

env:
  FARL_LOG: ${{ github.workspace }}/testing/test.log
  FARL_MAPPINGS: ${{ github.workspace }}/testing/test.yaml
  VALGRIND_LOG: ${{ github.workspace }}/testing/valgrind.log

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true
      - name: Build tester
        run: |
          cd testing
          make all
      - name: Install valgrind
        run: |
          sudo apt install --no-install-recommends -y valgrind
      - name: Run valgrind
        run: |
          valgrind --leak-check=full \
                   --show-leak-kinds=all \
                   --track-origins=yes \
                   --verbose \
                   testing/test
