name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

env:
  FARL_LOG: ${{ env.GITHUB_WORKSPACE }}/testing/test.log
  FARL_YAML: ${{ env.GITHUB_WORKSPACE }}/testing/test.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true
      - name: build
        run: |
          cd testing
          make all
      - name: testing
        run: testing/test
      - name: valgrind
        run: |
          valgrind --leak-check=full \
                   --show-leak-kinds=all \
                   --track-origins=yes \
                   --verbose \
                   --log-file=valgrind-out.txt \
                   testing/test
