name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true
      - name: build tester
        run: |
          cd testing
          make all
      - name: install valgrind
        run: apt install --no-install-recommends valgrind
      - name: run valgrind
        run: |
          valgrind --leak-check=full \
                   --show-leak-kinds=all \
                   --track-origins=yes \
                   --verbose \
                   --log-file=valgrind-out.txt \
                   testing/test
        env:
          FARL_LOG: ${{ env.GITHUB_WORKSPACE }}/testing/test.log
          FARL_YAML: ${{ env.GITHUB_WORKSPACE }}/testing/test.yaml
