name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true
      - name: Build tester
        run: |
          cd testing
          make all
      - name: Run tester
        run: |
          FARL_LOG=./test.log FARL_YAML=./test.yaml ./test
